
#ifndef _P99LOGIN_ERRORS_H_
#define _P99LOGIN_ERRORS_H_

enum Errors
{
    ERR_NONE,
    ERR_GETADDRINFO_CALL,
    ERR_SOCKET_CALL,
    ERR_BIND_CALL,
    ERR_FNCTL_FLAGS_INVALID,
    ERR_RECVFROM,
    ERR_SENDTO,
    ERR_WSASTARTUP,
    ERR_BAD_ALLOC
};

#endif/*_P99LOGIN_ERRORS_H_*/
